export const EXPEDIENTES_LIST_REQUEST = 'EXPEDIENTES_LIST_REQUEST'
export const EXPEDIENTES_LIST_SUCCESS = 'EXPEDIENTES_LIST_SUCCESS'
export const EXPEDIENTES_LIST_FAIL  = 'EXPEDIENTES_LIST_FAIL'

export const EXPEDIENTES_DETAILS_REQUEST = 'EXPEDIENTES_DETAILS_REQUEST'
export const EXPEDIENTES_DETAILS_SUCCESS = 'EXPEDIENTES_DETAILS_SUCCESS'
export const EXPEDIENTES_DETAILS_FAIL  = 'EXPEDIENTES_DETAILS_FAIL'