export const EXPEDIENTES_LIST_REQUEST = 'EXPEDIENTES_LIST_REQUEST'
export const EXPEDIENTES_LIST_SUCCESS = 'EXPEDIENTES_LIST_SUCCESS'
export const EXPEDIENTES_LIST_FAIL  = 'EXPEDIENTES_LIST_FAIL'

export const EXPEDIENTES_DETAILS_REQUEST = 'EXPEDIENTES_DETAILS_REQUEST'
export const EXPEDIENTES_DETAILS_SUCCESS = 'EXPEDIENTES_DETAILS_SUCCESS'
export const EXPEDIENTES_DETAILS_FAIL  = 'EXPEDIENTES_DETAILS_FAIL'

export const EXPEDIENTES_DELETE_REQUEST = 'EXPEDIENTES_DELETE_REQUEST'
export const EXPEDIENTES_DELETE_SUCCESS = 'EXPEDIENTES_DELETE_SUCCESS'
export const EXPEDIENTES_DELETE_FAIL  = 'EXPEDIENTES_DELETE_FAIL'

export const EXPEDIENTES_CREATE_REQUEST = 'EXPEDIENTES_CREATE_REQUEST'
export const EXPEDIENTES_CREATE_SUCCESS = 'EXPEDIENTES_CREATE_SUCCESS'
export const EXPEDIENTES_CREATE_FAIL  = 'EXPEDIENTES_CREATE_FAIL'
export const EXPEDIENTES_CREATE_RESET  = 'EXPEDIENTES_CREATE_RESET'

export const EXPEDIENTES_UPDATE_REQUEST = 'EXPEDIENTES_UPDATE_REQUEST'
export const EXPEDIENTES_UPDATE_SUCCESS = 'EXPEDIENTES_UPDATE_SUCCESS'
export const EXPEDIENTES_UPDATE_FAIL  = 'EXPEDIENTES_UPDATE_FAIL'
export const EXPEDIENTES_UPDATE_RESET  = 'EXPEDIENTES_UPDATE_RESET'

export const EXPEDIENTES_CREATE_ENTRADA_REQUEST = 'EXPEDIENTES_CREATE_ENTRADA_REQUEST'
export const EXPEDIENTES_CREATE_ENTRADA_SUCCESS = 'EXPEDIENTES_CREATE_ENTRADA_SUCCESS'
export const EXPEDIENTES_CREATE_ENTRADA_FAIL  = 'EXPEDIENTES_CREATE_ENTRADA_FAIL'
export const EXPEDIENTES_CREATE_ENTRADA_RESET  = 'EXPEDIENTES_CREATE_ENTRADA_RESET'

export const EXPEDIENTES_CREATE_DOCUMENT_REQUEST = 'EXPEDIENTES_CREATE_DOCUMENT_REQUEST'
export const EXPEDIENTES_CREATE_DOCUMENT_SUCCESS = 'EXPEDIENTES_CREATE_DOCUMENT_SUCCESS'
export const EXPEDIENTES_CREATE_DOCUMENT_FAIL  = 'EXPEDIENTES_CREATE_DOCUMENT_FAIL'
export const EXPEDIENTES_CREATE_DOCUMENT_RESET  = 'EXPEDIENTES_CREATE_DOCUMENT_RESET'