# Generated by Django 4.0.6 on 2022-11-21 03:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file', models.FileField(blank=True, null=True, upload_to=base.models.upload_path)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('dateUpload', models.DateField(blank=True, default='2022-11-21', null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('dateUpload', models.DateField(blank=True, default='2022-11-21', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('asignTo', models.CharField(blank=True, max_length=200, null=True)),
                ('contratist', models.CharField(blank=True, max_length=200, null=True)),
                ('direccionContratista', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipoFinanciamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('montoInicial', models.CharField(blank=True, max_length=200, null=True)),
                ('montoActualizado', models.CharField(blank=True, max_length=200, null=True)),
                ('pAvanceFisico', models.CharField(blank=True, max_length=200, null=True)),
                ('pAvanceFinanciero', models.CharField(blank=True, max_length=200, null=True)),
                ('stage', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('dateStart', models.DateField(default='2022-11-21')),
                ('dateEnd', models.DateField(default='2022-11-21')),
                ('description', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
