# Generated by Django 4.0.6 on 2022-10-24 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrada',
            name='Expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.expediente'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='Expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.expediente'),
        ),
    ]
