# Generated by Django 4.1.1 on 2022-09-21 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='21-09-2022'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='21-09-2022'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('dateUpload', models.DateField(default='21-09-2022')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.expediente')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.expediente')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
