# Generated by Django 4.0.6 on 2022-11-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dateUpload',
            field=models.DateField(blank=True, default='2022-11-23', null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateField(blank=True, default='2022-11-23', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='2022-11-23'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='2022-11-23'),
        ),
    ]
