# Generated by Django 4.0.6 on 2022-11-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_document_dateupload_alter_entrada_dateupload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='tipoFinanciamiento',
        ),
        migrations.AlterField(
            model_name='document',
            name='dateUpload',
            field=models.DateField(blank=True, default='2022-11-24', null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateField(blank=True, default='2022-11-24', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='2022-11-24'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='2022-11-24'),
        ),
    ]
