# Generated by Django 4.1.1 on 2022-09-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_comments_comment_rename_documents_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='dateUpload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
