# Generated by Django 4.1.1 on 2022-09-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_document_upload_file_alter_document_dateupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dateUpload',
            field=models.DateField(default='21-09-2022'),
        ),
    ]
