# Generated by Django 4.1.1 on 2022-09-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_document_dateupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='28-09-2022'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='28-09-2022'),
        ),
    ]
