# Generated by Django 4.0.6 on 2022-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_expediente_dateend_alter_expediente_datestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='09-10-2022'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='09-10-2022'),
        ),
    ]
