# Generated by Django 4.0.6 on 2022-10-12 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_comment_entrada_alter_expediente_dateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
