# Generated by Django 4.0.6 on 2022-10-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_entrada_dateupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='12-10-2022'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='12-10-2022'),
        ),
    ]
