# Generated by Django 4.0.6 on 2022-10-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_expediente_dateend_alter_expediente_datestart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='User',
            new_name='user',
        ),
    ]
