# Generated by Django 4.0.6 on 2022-10-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_user_entrada_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateTimeField(default='10/13/2022, 00:50:03'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='13-10-2022'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='13-10-2022'),
        ),
    ]
