# Generated by Django 4.0.6 on 2022-10-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_entrada_dateupload_alter_expediente_dateend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateTimeField(default='10/13/2022, 00:53:34'),
        ),
    ]
