# Generated by Django 4.0.6 on 2022-10-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_entrada_dateupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default='YYYYMMDD HH:mm:ss (20221013 01:17:35)', null=True),
        ),
    ]
