# Generated by Django 4.0.6 on 2022-10-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_entrada_dateupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateTimeField(blank=True, default='YYYY-MM-DD HH:mm:ss (20221013 01:18:19)', null=True),
        ),
    ]
