# Generated by Django 4.0.6 on 2022-10-19 07:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_entrada_dateupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='User',
        ),
        migrations.RemoveField(
            model_name='document',
            name='dateUpload',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_path),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='dateUpload',
            field=models.DateField(blank=True, default='2022-10-19', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateEnd',
            field=models.DateField(default='19-10-2022'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dateStart',
            field=models.DateField(default='19-10-2022'),
        ),
    ]
