# Generated by Django 4.0.6 on 2022-10-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='User',
        ),
        migrations.AddField(
            model_name='document',
            name='dateUpload',
            field=models.DateField(blank=True, default='2022-10-19', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
